name: osmis
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - python=3.8.3
  - pip
  - numpy=1.18.5
  - scipy=1.5.2
  - scikit-image=0.17.2
  - matplotlib=3.2.2
  - ipython=7.18.1
  - pillow=7.2.0
  - tqdm=4.48.2
  - requests=2.24.0
  - pyyaml=5.3.1
  - imageio=2.9.0
  - networkx=2.4
  - future=0.18.2
  - pyqt=5.9.2
  - sip=4.19.23
  - qt=5.9.7
  - joblib=0.16.0
  - cycler=0.10.0
  - kiwisolver=1.2.0
  - traitlets=4.3.3
  - decorator=4.4.2
  - typing_extensions>=4.5.0
  - pyopenssl=19.1.0
  - chardet=3.0.4
  - urllib3=1.25.11
  - certifi
  - tornado=6.0.4
  - toolz=0.10.0
  - pygments=2.6.1
  - jedi=0.17.2
  - prompt-toolkit=3.0.7
  - parso=0.7.0
  - readline=8.0
  - sqlite=3.32.3
  - zlib=1.2.11
  - openssl
  - tk=8.6.10
  - wheel
  - cudnn=8.9.2.26  
  - pytorch=2.1.1
  - torchvision=0.16.1
  - torchaudio=2.1.1
  - pytorch-cuda=11.8
  - pip:
    - kornia==0.6.10